### ISSUE TITLE
Demo Run the crash , because missing file

### ISSUE THREAD

**Issue by greezi** [pujiaxin33/JXTheme#4]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /JXTheme/Example/Example/ViewController.swift, line 162
![image](https://user-images.githubusercontent.com/13515835/67952611-87dfe700-fc28-11e9-9e80-590ae9ed548b.png)

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复
