### ISSUE TITLE
not support

### ISSUE THREAD

**Issue by LeoAiolia** [pujiaxin33/JXTheme#6]
let indicatorView: UIActivityIndicatorView 
调用
indicatorView.theme.color 
会报错，需要加下这个属性。
如果不加，至少可以让我们外部进行扩展，目前使用pod安装，外部进行扩展
```
extension ThemeWrapper where Base: UIActivityIndicatorView, T == UIColor {
    var color: ThemeProvider<UIColor>? {
        set(new) {
            let baseItem = self.base
            setupViewThemeProperty(view: self.base, key: "UIActivityIndicatorView.color", provider: new) {[weak baseItem] (style) in
                baseItem?.color = new?.provider(style)
            }
        }
        get { return self.base.providers["UIActivityIndicatorView.color"] as? ThemeProvider<UIColor> }
    }
}
```
会报错，Base is inaccessible due to 'internal' protection level

![图片](https://user-images.githubusercontent.com/16910025/84125547-4392b000-aa6f-11ea-83ca-c5801b804238.png)

**Comment by pujiaxin33** [comment]
感谢反馈，base属性可以外部访问。UIActivityIndicatorView.theme.color已经添加
