### ISSUE TITLE
optimize

### ISSUE THREAD

**Issue by LeoAiolia** [pujiaxin33/JXTheme#7]
当我设置了
```
button.theme.setTitleColor( ThemeProvider { UIColor.red }, for: .normal)
```
之后，又设置了（即：希望此button不跟随主题进行改变了。）
```
button.setTitleColor(.blue, for: .normal)
```

当调用改变主题的方法后，这个按钮的颜色跟随主题改变了。希望它不随主题改变。

**Comment by LeoAiolia** [comment]
```
button.theme.setTitleColor(ThemeProvider { UIColor.red }, for: .normal)
```

**Comment by pujiaxin33** [comment]
如果要实现你的需求，那么就需要swizzle UIButton的setTitleColor方法，然后把动态的ThemeProvider设置为nil。这样就就会导致有大量的swizzle方法出现。所以，你可以在`button.setTitleColor(.blue, for: .normal)`之后，调用`button.theme.setTitleColor( nil, for: .normal)`，来手动去掉动态变化。
