### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by LeoAiolia** [pujiaxin33/JXTheme#8]
![图片](https://user-images.githubusercontent.com/16910025/85371924-a0a85e80-b563-11ea-8390-ab73fcb4ef77.png)
部分手机，启动崩溃，应该是方法交换的地方有问题。

**Comment by LeoAiolia** [comment]
https://blog.csdn.net/weixin_34244102/article/details/93162030

**Comment by pujiaxin33** [comment]
感谢反馈，已修复
