### ISSUE TITLE
如何设置默认主题 how to get set default theme 

### ISSUE THREAD

**Issue by eric1202** [pujiaxin33/JXTheme#9]
extension ThemeStyle {
    static let blackGold = ThemeStyle(rawValue: "blackGold")
    static let tech = ThemeStyle(rawValue: "tech")
    static let ink = ThemeStyle(rawValue: "ink")
    
}

你好！感谢您的开源主题代码！
似乎并未能找到默认的设置入口？
比方说我默认要blackGold的主题 但是似乎切换过主题后重新安装app有些view的颜色会混乱
求指教
谢谢

**Comment by eric1202** [comment]
ThemeManager().changeTheme
ThemeManager().currentThemeStyle

**Comment by pujiaxin33** [comment]
调用ThemeManager的`func changeTheme(to style: ThemeStyle)`方法即可
